config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :media
  resources :statuses

  post '/comment' => 'media#comment' , :as => :comment_on_media

  get '/framework7' => 'framework#index' , :as => :framework
  get '/framework7/about' => 'framework#about' , :as => :framework_about

  root "media#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :media
end

app/models/medium.rb
class Medium < ActiveRecord::Base
    mount_uploader :video , MediaUploader
    has_many :comment
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :status
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/framework_controller.rb
class FrameworkController < ApplicationController
  #layout 'framework7' , :only => [:index , :about]

  def index
    @status = Status.new

    @collections = User.order(:id => :desc).all

    @media = Medium.order(:id => :desc).all

  end

  def about

  end

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :authenticate_user!
  before_action :set_medium, only: [:show, :comment, :edit, :update, :destroy]

  layout 'application'

  # GET /media
  # GET /media.json
  def index
    @media = Medium.order(:id => :desc).all
  end

  # GET /media/1
  # GET /media/1.json
  def show
      @comment = Comment.new
      #UserMailer.say_hi(@medium).deliver
  end

  # GET /media/new
  def new
    @medium = Medium.new
  end

  # GET /media/1/edit
  def edit
  end

  # POST /comment
  def comment
      comment = @medium.comment.build(comment_params)
      comment.save
      redirect_to @medium
  end

  # POST /media
  # POST /media.json
  def create
    @medium = Medium.new(medium_params)

    respond_to do |format|
      if @medium.save

        #视频更新成功通知
        #UserMailer.say_hi(@medium)

        format.html { redirect_to @medium, notice: 'Medium was successfully created.' }
        format.json { render :show, status: :created, location: @medium }
      else
        format.html { render :new }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1
  # PATCH/PUT /media/1.json
  def update
    respond_to do |format|
      if @medium.update(medium_params)
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
        format.json { render :show, status: :ok, location: @medium }
      else
        format.html { render :edit }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium.destroy
    respond_to do |format|
      format.html { redirect_to media_url, notice: 'Medium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medium
      @medium = Medium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medium_params
      params.require(:medium).permit(:subject, :description, :video)
    end

    def comment_params
        params.require(:comment).permit(:comment)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @statuses = Status.all
    respond_with(@statuses)
  end

  def show
    respond_with(@status)
  end

  def new
    @status = Status.new
    respond_with(@status)
  end

  def edit
  end

  def create
    @status = Status.new(status_params)
    @status.save
    respond_with(@status)
  end

  def update
    @status.update(status_params)
    respond_with(@status)
  end

  def destroy
    @status.destroy
    respond_with(@status)
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:status, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/framework/about.html.erb
Hello world

app/views/framework/index.html.erb
<% @media[2,5].each do |c| %>

    <p>
      <%= [c.id , c.subject]
          .join('.')
          .sub( /视频/ , '<span style="color:red">视频</span>')
          .sub( /试/ , '<span style="font-size: 120px;">试</span>')
          .html_safe %>
    </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-cn">
<head>
  <meta charset="utf-8">
  <title>VideoShare</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'media', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'swfobject' %>

  <%= stylesheet_link_tag    'mediaelementplayer', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'mediaelement-and-player.min', 'data-turbolinks-track' => true %>


</head>

<body>

<div class="container">

    <% if current_user %>
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
    <% else %>
        <%= link_to('註冊', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
    <% end %>

    <%= yield %>
</div>

<style>
body {
    background: url('<%= asset_path 'bg.png' %>')
}
</style>

</body>
</html>

app/views/layouts/framework7.html.erb
<!DOCTYPE html>
<html lang="zh-cn">
<head>
  <meta charset="utf-8">
  <title>VideoShare</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <%= stylesheet_link_tag    'framework7', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'swfobject' %>

</head>

<body>


<!-- Side bar left-->
<div class="panel-overlay"></div>

<div class="panel panel-left panel-reveal">
  <div class="content-block">
    <p>Left Panel content here</p>
    <p><a href="#" class="panel-close">Close me</a></p>
    <p><a href="#" class="open-right-panel">Open Right Panel</a></p>
  </div>
</div>

<div class="panel-overlay"></div>
<div class="panel panel-right panel-reveal">
  <div class="content-block">
    <p>Right Panel content here</p>
    <p><a href="#" class="panel-close">Close me</a></p>
    <p><a href="#" class="open-right-panel">Open Right Panel</a></p>
  </div>
</div>


<!-- Views -->
<div class="views">

    <%= yield %>

</div>

<%= javascript_include_tag 'framework7', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'app', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/media/_form.html.erb
<div class="row">
    <div class="col-md-6">
<%= form_for(@medium) do |f| %>
  <% if @medium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medium.errors.count, "error") %> prohibited this medium from being saved:</h2>

      <ul>
      <% @medium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :subject %><br>
    <%= f.text_field :subject , :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description , :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :video %><br>
    <%= f.file_field :video %>
  </div>
  <div class="form-group">
    <%= f.submit '更新视频' , :class => 'btn btn-success' %>
  </div>
<% end %>
    </div>
</div>

app/views/media/edit.html.erb
<h1>Editing medium</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<div class="row">
<h1>Media Library
    <small><%= link_to 'New Medium', new_medium_path , :class => 'btn btn-primary' %></small>

</h1>


    <% @media.each do |medium| %>
    <div class="col-md-4">
    <div class="panel">
        <div class="panel-body">
        <h3><%= medium.subject %></h3>
        <small><%= medium.description %></small>

          <video width="330" height="240"  poster="poster.jpg" controls="controls" preload=true>
            <!-- MP4 for Safari, IE9, iPhone, iPad, Android, and Windows Phone 7 -->
            <source type="video/mp4" src="<%= medium.video.url %>" />
            <!--<track kind="subtitles" src="subtitles.srt" srclang="en" />-->
            <!--<track kind="chapters" src="chapters.srt" srclang="en" />-->
            <!-- Flash fallback for non-HTML5 browsers without JavaScript -->
            <object height="350" type="application/x-shockwave-flash" data="flashmediaelement.swf">
              <param name="movie" value="flashmediaelement.swf" />
              <param name="flashvars" value="controls=true&file=<%= medium.video.url %>" />
              <!-- Image as a last resort -->
              <img src="myvideo.jpg" width="320" height="240" title="No video playback capabilities" />
            </object>
          </video>

        <%= link_to 'Show', medium %>
        <%= link_to 'Edit', edit_medium_path(medium) %>
        <%= link_to 'Destroy', medium, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
    </div>
    <% end %>

</div>

<script>
    $('video').mediaelementplayer({
        features: ['playpause','loop','current','progress','duration','volume' , 'fullscreen']

    });
</script>

app/views/media/new.html.erb
<h1>New medium</h1>

<%= render 'form' %>

<%= link_to 'Back', media_path %>

app/views/media/show.html.erb
<div class="row">

<div class="col-md-6">
    <div class="panel"><div class="panel-body">
        <h3>视频</h3>
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Subject:</strong>
      <%= @medium.subject %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @medium.description %>
    </p>

    <p>
      <video height="350"  poster="poster.jpg" controls="controls" preload=true>
        <!-- MP4 for Safari, IE9, iPhone, iPad, Android, and Windows Phone 7 -->
        <source type="video/mp4" src="<%= @medium.video.url %>" />
        <!--<track kind="subtitles" src="subtitles.srt" srclang="en" />-->
        <!--<track kind="chapters" src="chapters.srt" srclang="en" />-->
        <!-- Flash fallback for non-HTML5 browsers without JavaScript -->
        <object height="350" type="application/x-shockwave-flash" data="flashmediaelement.swf">
          <param name="movie" value="flashmediaelement.swf" />
          <param name="flashvars" value="controls=true&file=<%= @medium.video.url %>" />
          <!-- Image as a last resort -->
          <img src="myvideo.jpg" width="320" height="240" title="No video playback capabilities" />
        </object>
      </video>

    </p>

    <%= link_to 'Edit', edit_medium_path(@medium) %> |
    <%= link_to 'Back', media_path %>
    </div></div>
</div>

<div class="col-md-6">

    <div class="panel">
    <div class="panel-body">
        <h3>建议</h3>

        <%= form_for @comment , :url => url_for(:controller => '/media' , :action => 'comment' , :id => @medium.id) , :method => 'post' do |f| %>

        <div class="form-group">
            <%= f.text_area :comment , :class => 'form-control'%>
        </div>

        <div class="form-group">
            <%=f.submit '发建议' , :class => 'btn btn-primary'%>
        </div>

        <% @medium.comment.order(:id => :desc).each do |c| %>
            <p><%= c.comment %></p>
        <% end %>

        <% end %>

    </div>
    </div>

</div>
</div>

<script>
    $('video').mediaelementplayer({
        features: ['playpause','loop','current','progress','duration','volume' , 'fullscreen']

    });
</script>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_area :status %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.status %></td>
        <td><%= status.user_id %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @status.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @status.user_id %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>